name: addis_ai_sdk
description: "Flutter SDK for Addis AI API, supporting Ethiopian languages like Amharic and Afan Oromo."
version: 0.1.0
homepage: https://platform.addisassistant.com
repository: https://github.com/addisai/addis_ai_flutter_sdk

environment:
  sdk: ^3.2.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  mime: ^1.0.6
  http_parser: ^4.1.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.0
